import { UnionGrade } from "@core/types/UnionGrade";
import Position from "@core/classes/Position";
import Trapezoid from "@core/classes/Trapezoid";
import { EXTERNAL_AREA, JOB, JOB_GROUP } from "@core/enums";
import { ExternalAreaInfo } from "@core/types/ExternalAreaInfo";
import { JobInfo } from "@core/types/JobInfo";

export const UNION_BOARD_WIDTH = 22;
export const UNION_BOARD_HEIGHT = 20;
export const DEFAULT_AREA_WIDTH = 6;
export const DEFAULT_AREA_HEIGHT = 5;
export const SELECT_WORLD_CHARACTER = "월드/캐릭터";
export const DEFAULT_OCCUPATION_LEVEL = 6;
export const MAX_ITERATION_COUNT = 100000;
export const CARD_PER_PAGE = 4;
export const CARD_WIDTH = "11.6rem"
export const EXTERNAL_AREA_MAP: Readonly<{ [key in EXTERNAL_AREA]: ExternalAreaInfo }> = {
    [EXTERNAL_AREA.크리티컬데미지]: {
        trapezoid: new Trapezoid([
            new Position(9, 4),
            new Position(9, 0),
            new Position(6, 4),
            new Position(0, 0),
        ]),
        startPosition: new Position(9, 4),
        intersectingArea: [
            new Position(0, 0),
            new Position(1, 1),
            new Position(2, 2),
            new Position(3, 3),
            new Position(4, 4),
            new Position(9, 0),
            new Position(9, 1),
            new Position(9, 2),
            new Position(9, 3),
            new Position(9, 4),
        ],
    },
    [EXTERNAL_AREA.방어율무시]: {
        trapezoid: new Trapezoid([
            new Position(10, 4),
            new Position(10, 0),
            new Position(15, 4),
            new Position(19, 0),
        ]),
        startPosition: new Position(10, 4),
        intersectingArea: [
            new Position(15, 4),
            new Position(16, 3),
            new Position(17, 2),
            new Position(18, 1),
            new Position(19, 0),
            new Position(10, 0),
            new Position(10, 1),
            new Position(10, 2),
            new Position(10, 3),
            new Position(10, 4),
        ],
    },
    [EXTERNAL_AREA.버프지속시간]: {
        trapezoid: new Trapezoid([
            new Position(15, 10),
            new Position(15, 5),
            new Position(19, 10),
            new Position(19, 1),
        ]),
        startPosition: new Position(15, 10),
        intersectingArea: [
            new Position(15, 5),
            new Position(16, 4),
            new Position(17, 3),
            new Position(18, 2),
            new Position(19, 1),
            new Position(15, 10),
            new Position(16, 10),
            new Position(17, 10),
            new Position(18, 10),
            new Position(19, 10),
        ],
    },
    [EXTERNAL_AREA.일반데미지]: {
        trapezoid: new Trapezoid([
            new Position(15, 11),
            new Position(15, 16),
            new Position(19, 11),
            new Position(19, 20),
        ]),
        startPosition: new Position(15, 11),
        intersectingArea: [
            new Position(15, 16),
            new Position(16, 17),
            new Position(17, 18),
            new Position(18, 19),
            new Position(19, 20),
            new Position(15, 11),
            new Position(16, 11),
            new Position(17, 11),
            new Position(18, 11),
            new Position(19, 11),
        ],
    },
    [EXTERNAL_AREA.보스데미지]: {
        trapezoid: new Trapezoid([
            new Position(10, 17),
            new Position(15, 17),
            new Position(10, 21),
            new Position(19, 21),
        ]),
        startPosition: new Position(10, 17),
        intersectingArea: [
            new Position(15, 17),
            new Position(16, 18),
            new Position(17, 19),
            new Position(18, 20),
            new Position(19, 21),
            new Position(10, 17),
            new Position(10, 18),
            new Position(10, 19),
            new Position(10, 20),
            new Position(10, 21),
        ],
    },
    [EXTERNAL_AREA.크리티컬확률]: {
        trapezoid: new Trapezoid([
            new Position(9, 17),
            new Position(9, 21),
            new Position(4, 17),
            new Position(0, 21),
        ]),
        startPosition: new Position(9, 17),
        intersectingArea: [
            new Position(4, 17),
            new Position(3, 18),
            new Position(2, 19),
            new Position(1, 20),
            new Position(0, 21),
            new Position(9, 18),
            new Position(9, 17),
            new Position(9, 19),
            new Position(9, 20),
            new Position(9, 21),
        ],
    },
    [EXTERNAL_AREA.획득경험치]: {
        trapezoid: new Trapezoid([
            new Position(4, 11),
            new Position(4, 16),
            new Position(0, 11),
            new Position(0, 20),
        ]),
        startPosition: new Position(4, 11),
        intersectingArea: [
            new Position(4, 16),
            new Position(3, 17),
            new Position(2, 18),
            new Position(1, 19),
            new Position(0, 20),
            new Position(4, 11),
            new Position(3, 11),
            new Position(2, 11),
            new Position(1, 11),
            new Position(0, 11),
        ],
    },
    [EXTERNAL_AREA.상태이상내성]: {
        trapezoid: new Trapezoid([
            new Position(4, 5),
            new Position(4, 10),
            new Position(0, 1),
            new Position(0, 10),
        ]),
        startPosition: new Position(4, 10),
        intersectingArea: [
            new Position(4, 5),
            new Position(3, 4),
            new Position(2, 3),
            new Position(1, 2),
            new Position(0, 1),
            new Position(4, 10),
            new Position(3, 10),
            new Position(2, 10),
            new Position(1, 10),
            new Position(0, 10),
        ],
    },
};

export const EXTERNAL_AREA_MAP2: Readonly<{ [key in EXTERNAL_AREA]: Position[] }> = {
    [EXTERNAL_AREA.크리티컬데미지]: [
        new Position(9, 4),
        new Position(8, 4),
        new Position(7, 4),
        new Position(6, 4),
        new Position(5, 4),
        new Position(4, 4),
        new Position(9, 3),
        new Position(8, 3),
        new Position(7, 3),
        new Position(6, 3),
        new Position(5, 3),
        new Position(4, 3),
        new Position(4, 3),
        new Position(3, 3),
        new Position(9, 2),
        new Position(8, 2),
        new Position(7, 2),
        new Position(6, 2),
        new Position(5, 2),
        new Position(4, 2),
        new Position(4, 2),
        new Position(3, 2),
        new Position(2, 2),
        new Position(9, 1),
        new Position(8, 1),
        new Position(7, 1),
        new Position(6, 1),
        new Position(5, 1),
        new Position(4, 1),
        new Position(4, 1),
        new Position(3, 1),
        new Position(2, 1),
        new Position(1, 1),
        new Position(9, 0),
        new Position(8, 0),
        new Position(7, 0),
        new Position(6, 0),
        new Position(5, 0),
        new Position(4, 0),
        new Position(4, 0),
        new Position(3, 0),
        new Position(2, 0),
        new Position(1, 0),
        new Position(0, 0),
    ],
    [EXTERNAL_AREA.방어율무시]: [
        new Position(10, 4),
        new Position(11, 4),
        new Position(12, 4),
        new Position(13, 4),
        new Position(14, 4),
        new Position(15, 4),
        new Position(10, 3),
        new Position(11, 3),
        new Position(12, 3),
        new Position(13, 3),
        new Position(14, 3),
        new Position(15, 3),
        new Position(16, 3),
        new Position(10, 2),
        new Position(11, 2),
        new Position(12, 2),
        new Position(13, 2),
        new Position(14, 2),
        new Position(15, 2),
        new Position(16, 2),
        new Position(17, 2),
        new Position(10, 1),
        new Position(11, 1),
        new Position(12, 1),
        new Position(13, 1),
        new Position(14, 1),
        new Position(15, 1),
        new Position(16, 1),
        new Position(17, 1),
        new Position(18, 1),
        new Position(10, 0),
        new Position(11, 0),
        new Position(12, 0),
        new Position(13, 0),
        new Position(14, 0),
        new Position(15, 0),
        new Position(16, 0),
        new Position(17, 0),
        new Position(18, 0),
        new Position(19, 0),
    ],
    [EXTERNAL_AREA.버프지속시간]: [
        new Position(15, 10),
        new Position(15, 9),
        new Position(15, 8),
        new Position(15, 7),
        new Position(15, 6),
        new Position(15, 5),
        new Position(16, 10),
        new Position(16, 9),
        new Position(16, 8),
        new Position(16, 7),
        new Position(16, 6),
        new Position(16, 5),
        new Position(16, 4),
        new Position(17, 10),
        new Position(17, 9),
        new Position(17, 8),
        new Position(17, 7),
        new Position(17, 6),
        new Position(17, 5),
        new Position(17, 4),
        new Position(17, 3),
        new Position(18, 10),
        new Position(18, 9),
        new Position(18, 8),
        new Position(18, 7),
        new Position(18, 6),
        new Position(18, 5),
        new Position(18, 4),
        new Position(18, 3),
        new Position(18, 2),
        new Position(19, 10),
        new Position(19, 9),
        new Position(19, 8),
        new Position(19, 7),
        new Position(19, 6),
        new Position(19, 5),
        new Position(19, 4),
        new Position(19, 3),
        new Position(19, 2),
        new Position(19, 1),
    ],
    [EXTERNAL_AREA.일반데미지]: [
        new Position(15, 11),
        new Position(15, 12),
        new Position(15, 13),
        new Position(15, 14),
        new Position(15, 15),
        new Position(15, 16),
        new Position(16, 11),
        new Position(16, 12),
        new Position(16, 13),
        new Position(16, 14),
        new Position(16, 15),
        new Position(16, 16),
        new Position(16, 17),
        new Position(17, 11),
        new Position(17, 12),
        new Position(17, 13),
        new Position(17, 14),
        new Position(17, 15),
        new Position(17, 16),
        new Position(17, 17),
        new Position(17, 18),
        new Position(18, 11),
        new Position(18, 12),
        new Position(18, 13),
        new Position(18, 14),
        new Position(18, 15),
        new Position(18, 16),
        new Position(18, 17),
        new Position(18, 18),
        new Position(18, 19),
        new Position(19, 11),
        new Position(19, 12),
        new Position(19, 13),
        new Position(19, 14),
        new Position(19, 15),
        new Position(19, 16),
        new Position(19, 17),
        new Position(19, 18),
        new Position(19, 19),
        new Position(19, 20),
    ],
    [EXTERNAL_AREA.보스데미지]: [
        new Position(10, 17),
        new Position(11, 17),
        new Position(12, 17),
        new Position(13, 17),
        new Position(14, 17),
        new Position(15, 17),
        new Position(10, 18),
        new Position(11, 18),
        new Position(12, 18),
        new Position(13, 18),
        new Position(14, 18),
        new Position(15, 18),
        new Position(16, 18),
        new Position(10, 19),
        new Position(11, 19),
        new Position(12, 19),
        new Position(13, 19),
        new Position(14, 19),
        new Position(15, 19),
        new Position(16, 19),
        new Position(17, 19),
        new Position(10, 20),
        new Position(11, 20),
        new Position(12, 20),
        new Position(13, 20),
        new Position(14, 20),
        new Position(15, 20),
        new Position(16, 20),
        new Position(17, 20),
        new Position(18, 20),
        new Position(10, 21),
        new Position(11, 21),
        new Position(12, 21),
        new Position(13, 21),
        new Position(14, 21),
        new Position(15, 21),
        new Position(16, 21),
        new Position(17, 21),
        new Position(18, 21),
        new Position(19, 21),
    ],
    [EXTERNAL_AREA.크리티컬확률]: [
        new Position(9, 17),
        new Position(8, 17),
        new Position(7, 17),
        new Position(6, 17),
        new Position(5, 17),
        new Position(4, 17),
        new Position(9, 18),
        new Position(8, 18),
        new Position(7, 18),
        new Position(6, 18),
        new Position(5, 18),
        new Position(4, 18),
        new Position(4, 18),
        new Position(3, 18),
        new Position(9, 19),
        new Position(8, 19),
        new Position(7, 19),
        new Position(6, 19),
        new Position(5, 19),
        new Position(4, 19),
        new Position(4, 19),
        new Position(3, 19),
        new Position(2, 19),
        new Position(9, 20),
        new Position(8, 20),
        new Position(7, 20),
        new Position(6, 20),
        new Position(5, 20),
        new Position(4, 20),
        new Position(4, 20),
        new Position(3, 20),
        new Position(2, 20),
        new Position(2, 20),
        new Position(9, 21),
        new Position(8, 21),
        new Position(7, 21),
        new Position(6, 21),
        new Position(5, 21),
        new Position(4, 21),
        new Position(4, 21),
        new Position(3, 21),
        new Position(2, 21),
        new Position(2, 21),
        new Position(2, 21),
    ],
    [EXTERNAL_AREA.획득경험치]: [
        new Position(4, 11),
        new Position(4, 12),
        new Position(4, 13),
        new Position(4, 14),
        new Position(4, 15),
        new Position(4, 16),
        new Position(3, 11),
        new Position(3, 12),
        new Position(3, 13),
        new Position(3, 14),
        new Position(3, 15),
        new Position(3, 16),
        new Position(3, 17),
        new Position(2, 11),
        new Position(2, 12),
        new Position(2, 13),
        new Position(2, 14),
        new Position(2, 15),
        new Position(2, 16),
        new Position(2, 17),
        new Position(2, 18),
        new Position(1, 11),
        new Position(1, 12),
        new Position(1, 13),
        new Position(1, 14),
        new Position(1, 15),
        new Position(1, 16),
        new Position(1, 17),
        new Position(1, 18),
        new Position(1, 19),
        new Position(0, 11),
        new Position(0, 12),
        new Position(0, 13),
        new Position(0, 14),
        new Position(0, 15),
        new Position(0, 16),
        new Position(0, 17),
        new Position(0, 18),
        new Position(0, 19),
        new Position(0, 20),
    ],
    [EXTERNAL_AREA.상태이상내성]: [
        new Position(4, 10),
        new Position(4, 9),
        new Position(4, 8),
        new Position(4, 7),
        new Position(4, 6),
        new Position(4, 5),
        new Position(3, 10),
        new Position(3, 9),
        new Position(3, 8),
        new Position(3, 7),
        new Position(3, 6),
        new Position(3, 5),
        new Position(3, 4),
        new Position(2, 10),
        new Position(2, 9),
        new Position(2, 8),
        new Position(2, 7),
        new Position(2, 6),
        new Position(2, 5),
        new Position(2, 4),
        new Position(2, 3),
        new Position(1, 10),
        new Position(1, 9),
        new Position(1, 8),
        new Position(1, 7),
        new Position(1, 6),
        new Position(1, 5),
        new Position(1, 4),
        new Position(1, 3),
        new Position(1, 2),
        new Position(0, 10),
        new Position(0, 9),
        new Position(0, 8),
        new Position(0, 7),
        new Position(0, 6),
        new Position(0, 5),
        new Position(0, 4),
        new Position(0, 3),
        new Position(0, 2),
        new Position(0, 1),
    ],
};

export const JOB_MAP: Readonly<{ [key: string]: JobInfo }> = {
    파이터: { name: JOB.히어로, group: JOB_GROUP.전사 },
    크루세이더: { name: JOB.히어로, group: JOB_GROUP.전사 },
    히어로: { name: JOB.히어로, group: JOB_GROUP.전사 },
    페이지: { name: JOB.팔라딘, group: JOB_GROUP.전사 },
    나이트: { name: JOB.팔라딘, group: JOB_GROUP.전사 },
    팔라딘: { name: JOB.팔라딘, group: JOB_GROUP.전사 },
    스피어맨: { name: JOB.다크나이트, group: JOB_GROUP.전사 },
    버서커: { name: JOB.다크나이트, group: JOB_GROUP.전사 },
    다크나이트: { name: JOB.다크나이트, group: JOB_GROUP.전사 },
    "위자드(불,독)": { name: JOB["아크메이지(불,독)"], group: JOB_GROUP.마법사 },
    "메이지(불,독)": { name: JOB["아크메이지(불,독)"], group: JOB_GROUP.마법사 },
    "아크메이지(불,독)": { name: JOB["아크메이지(불,독)"], group: JOB_GROUP.마법사 },
    "위자드(썬,콜)": { name: JOB["아크메이지(썬,콜)"], group: JOB_GROUP.마법사 },
    "메이지(썬,콜)": { name: JOB["아크메이지(썬,콜)"], group: JOB_GROUP.마법사 },
    "아크메이지(썬,콜)": { name: JOB["아크메이지(썬,콜)"], group: JOB_GROUP.마법사 },
    클레릭: { name: JOB.비숍, group: JOB_GROUP.마법사 },
    프리스트: { name: JOB.비숍, group: JOB_GROUP.마법사 },
    비숍: { name: JOB.비숍, group: JOB_GROUP.마법사 },
    헌터: { name: JOB.보우마스터, group: JOB_GROUP.궁수 },
    레인저: { name: JOB.보우마스터, group: JOB_GROUP.궁수 },
    보우마스터: { name: JOB.보우마스터, group: JOB_GROUP.궁수 },
    사수: { name: JOB.신궁, group: JOB_GROUP.궁수 },
    저격수: { name: JOB.신궁, group: JOB_GROUP.궁수 },
    신궁: { name: JOB.신궁, group: JOB_GROUP.궁수 },
    체이서: { name: JOB.패스파인더, group: JOB_GROUP.궁수 },
    "에인션트 아처": { name: JOB.패스파인더, group: JOB_GROUP.궁수 },
    패스파인더: { name: JOB.패스파인더, group: JOB_GROUP.궁수 },
    어쌔신: { name: JOB.나이트로드, group: JOB_GROUP.도적 },
    허밋: { name: JOB.나이트로드, group: JOB_GROUP.도적 },
    나이트로드: { name: JOB.나이트로드, group: JOB_GROUP.도적 },
    시프: { name: JOB.섀도어, group: JOB_GROUP.도적 },
    시프마스터: { name: JOB.섀도어, group: JOB_GROUP.도적 },
    섀도어: { name: JOB.섀도어, group: JOB_GROUP.도적 },
    듀얼블레이드: { name: JOB.듀얼블레이더, group: JOB_GROUP.도적 },
    세미듀어러: { name: JOB.듀얼블레이더, group: JOB_GROUP.도적 },
    듀어러: { name: JOB.듀얼블레이더, group: JOB_GROUP.도적 },
    듀얼마스터: { name: JOB.듀얼블레이더, group: JOB_GROUP.도적 },
    슬래셔: { name: JOB.듀얼블레이더, group: JOB_GROUP.도적 },
    듀얼블레이더: { name: JOB.듀얼블레이더, group: JOB_GROUP.도적 },
    인파이터: { name: JOB.바이퍼, group: JOB_GROUP.해적 },
    버커니어: { name: JOB.바이퍼, group: JOB_GROUP.해적 },
    바이퍼: { name: JOB.바이퍼, group: JOB_GROUP.해적 },
    건슬링거: { name: JOB.캡틴, group: JOB_GROUP.해적 },
    발키리: { name: JOB.캡틴, group: JOB_GROUP.해적 },
    캡틴: { name: JOB.캡틴, group: JOB_GROUP.해적 },
    캐논슈터: { name: JOB.캐논슈터, group: JOB_GROUP.해적 },
    캐논블래스터: { name: JOB.캐논슈터, group: JOB_GROUP.해적 },
    캐논마스터: { name: JOB.캐논슈터, group: JOB_GROUP.해적 },
    소울마스터: { name: JOB.소울마스터, group: JOB_GROUP.전사 },
    플레임위자드: { name: JOB.플레임위자드, group: JOB_GROUP.마법사 },
    윈드브레이커: { name: JOB.윈드브레이커, group: JOB_GROUP.궁수 },
    나이트워커: { name: JOB.나이트워커, group: JOB_GROUP.도적 },
    스트라이커: { name: JOB.스트라이커, group: JOB_GROUP.해적 },
    미하일: { name: JOB.미하일, group: JOB_GROUP.전사 },
    블래스터: { name: JOB.블래스터, group: JOB_GROUP.전사 },
    배틀메이지: { name: JOB.배틀메이지, group: JOB_GROUP.마법사 },
    와일드헌터: { name: JOB.와일드헌터, group: JOB_GROUP.궁수 },
    메카닉: { name: JOB.메카닉, group: JOB_GROUP.해적 },
    데몬슬레이어: { name: JOB.데몬슬레이어, group: JOB_GROUP.전사 },
    데몬어벤져: { name: JOB.데몬어벤져, group: JOB_GROUP.전사 },
    제논: { name: JOB.제논, group: JOB_GROUP.제논 },
    아란: { name: JOB.아란, group: JOB_GROUP.전사 },
    에반: { name: JOB.에반, group: JOB_GROUP.마법사 },
    메르세데스: { name: JOB.메르세데스, group: JOB_GROUP.궁수 },
    팬텀: { name: JOB.팬텀, group: JOB_GROUP.도적 },
    은월: { name: JOB.은월, group: JOB_GROUP.해적 },
    루미너스: { name: JOB.루미너스, group: JOB_GROUP.마법사 },
    카이저: { name: JOB.카이저, group: JOB_GROUP.전사 },
    카인: { name: JOB.카인, group: JOB_GROUP.궁수 },
    카데나: { name: JOB.카데나, group: JOB_GROUP.도적 },
    엔젤릭버스터: { name: JOB.엔젤릭버스터, group: JOB_GROUP.해적 },
    아델: { name: JOB.아델, group: JOB_GROUP.전사 },
    일리움: { name: JOB.일리움, group: JOB_GROUP.마법사 },
    칼리: { name: JOB.칼리, group: JOB_GROUP.도적 },
    아크: { name: JOB.아크, group: JOB_GROUP.해적 },
    라라: { name: JOB.라라, group: JOB_GROUP.마법사 },
    호영: { name: JOB.호영, group: JOB_GROUP.도적 },
    제로: { name: JOB.제로, group: JOB_GROUP.전사 },
    키네시스: { name: JOB.키네시스, group: JOB_GROUP.마법사 },
};

export const UNION_GRADE: { [key: string]: UnionGrade } = {
    NO_GRADE: {
        blockCount: 0,
        occupiableLevel: 0,
    },
    NOVICE_1: {
        blockCount: 9,
        occupiableLevel: 0,
    },
    NOVICE_2: {
        blockCount: 10,
        occupiableLevel: 0,
    },
    NOVICE_3: {
        blockCount: 11,
        occupiableLevel: 0,
    },
    NOVICE_4: {
        blockCount: 12,
        occupiableLevel: 1,
    },
    NOVICE_5: {
        blockCount: 13,
        occupiableLevel: 1,
    },
    VETERAN_1: {
        blockCount: 18,
        occupiableLevel: 2,
    },
    VETERAN_2: {
        blockCount: 19,
        occupiableLevel: 2,
    },
    VETERAN_3: {
        blockCount: 20,
        occupiableLevel: 3,
    },
    VETERAN_4: {
        blockCount: 21,
        occupiableLevel: 3,
    },
    VETERAN_5: {
        blockCount: 22,
        occupiableLevel: 4,
    },
    MASTER_1: {
        blockCount: 27,
        occupiableLevel: 4,
    },
    MASTER_2: {
        blockCount: 28,
        occupiableLevel: 5,
    },
    MASTER_3: {
        blockCount: 29,
        occupiableLevel: 5,
    },
    MASTER_4: {
        blockCount: 30,
        occupiableLevel: 5,
    },
    MASTER_5: {
        blockCount: 31,
        occupiableLevel: 5,
    },
    GRANDMASTER_1: {
        blockCount: 36,
        occupiableLevel: 5,
    },
    GRANDMASTER_2: {
        blockCount: 37,
        occupiableLevel: 5,
    },
    GRANDMASTER_3: {
        blockCount: 38,
        occupiableLevel: 5,
    },
    GRANDMASTER_4: {
        blockCount: 39,
        occupiableLevel: 5,
    },
    GRANDMASTER_5: {
        blockCount: 40,
        occupiableLevel: 5,
    },
    SUPREME_1: {
        blockCount: 41,
        occupiableLevel: 5,
    },
    SUPREME_2: {
        blockCount: 42,
        occupiableLevel: 5,
    },
    SUPREME_3: {
        blockCount: 43,
        occupiableLevel: 5,
    },
    SUPREME_4: {
        blockCount: 44,
        occupiableLevel: 5,
    },
    SUPREME_5: {
        blockCount: 45,
        occupiableLevel: 5,
    },
};

export const SQUARE_UNICODE = {
    RED: "\uD83D\uDFE5",
    BLUE: "🟣️",
    // BLUE: "\uD83D\uDFE6",
    GREEN: "\uD83D\uDFE9",
    YELLOW: "\uD83D\uDFE8",
    ORANGE: "\uD83D\uDFE7",
};